server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8761:8761/eureka/
  instance:
    prefer-ip-address: true