server:
  port: 8762
spring:
  application:
    name: microservice-discovery-eureka
eureka:
  instance:
    hostname: eureka8762
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka/
#    register-with-eureka: false
#    fetch-registry: false